### PR TITLE
added entry for Currying

### PR DESCRIPTION
**Pull request by dstorrs**

### CODE REVIEW

**Comment by dumaron** [comment]
Sorry to disturb, maybe this is not the place for this discussion, but by reading the proposed definition of `curry` I got a little confused. I need to say that:
1. I am not a native English speaker
2. I have a naive understanding of functional programming
3. I'm a Racket newbie

So probably I'm not a good candidate for discussing a PR on glossary, but I taught this was a chance to improve it for more inexperienced users.

Is Racket's `curry` actually more a partial application? With my naive understanding of functional programming, I think that unless you end up not having procedures that takes exactly one argument at once, you're actually doing more partial application.

So, if we take the code in the PR:
```scheme
(define draw-line-from-origin (curry draw-line 0 0))
```

What I would expect from currying is:
```scheme
(define draw-line-from-origin ((curry draw-line 0) 0))
```
 Am I wrong? And, even if I am, is there a chance to improve the explanation to address this possible source of confusion?

**Comment by sschwarzer** [comment]
@dumaron, thanks for chiming in. :-)

> maybe this is not the place for this discussion

It may be unusual in a PR, but since it's related to the PR, why not? :-)

> So probably I'm not a good candidate for discussing a PR on glossary

Actually, I think you're an _excellent_ candidate - because you belong to the target audience of the glossary (or at the moment, to-be glossary ;-) ).

> Is Racket's curry actually more a partial application?

Yes.

Regarding the code example,
```scheme
(define draw-line-from-origin (curry draw-line 0 0))
```
makes sense. `(curry draw-line 0 0)` returns a function that is like `draw-line`, but has `from-x` and `from-y` (with values 0) already applied. (`curry` can "pre-apply" more than one argument.) The `define` binds the return value from `curry` to the name `draw-line-from-origin`, so `draw-line-from-origin` now is the curried/partially applied function.

Your code
```scheme
(define draw-line-from-origin ((curry draw-line 0) 0))
```
would create a curried function `(curry draw-line 0)` with a fixed `from-x` argument 0, i.e. the returned function would still take three more arguments. If you use this function in `((curry draw-line 0) 0)`, you apply a function that still takes three arguments to a single argument 0, which would give you an arity (i.e. wrong number of arguments) exception.

> And, even if I am, is there a chance to improve the explanation to address this possible source of confusion?

The information in `glossary_notes.md` is intended as starting points for actual glossary entries, so the example that @dstorrs provided may not be the example that ends up in the glossary, or it may, but with additional explanation. (I _was_ planning to use the "classic" "adder" example, but I like @dstorrs's example actually more. The example seems more useful, and it shows that `curry` can take more than one argument beside the original function.)

(If I don't forget) I'll try to take this discussion into account when I write the actual glossary entry.

**Comment by sschwarzer** [comment]
@dstorrs, thanks for your PR! :-) My feedback, apart from the feedback in the previous comment :-) ...

- Please change your commit message to follow https://cbea.ms/git-commit/ . In your case you only need to change the subject line, but _if_ you want to explain a bit more why you wrote what you wrote (e.g. a motivation for the specific example), the commit message body may be a good place.
- I think a bullet point style works better for the notes. Can you please split the PR in sensible bullet points (maybe one for the definition at the start, one for the example and one for `curry` and `curryr`?) I think splitting notes is useful because it makes it easier for others to add more notes. If the "Currying" section would be your PR, it may seem to others that this essentially is the glossary entry and might be discouraged to add more notes/thoughts.

You may already know this, but just in case you don't: You can change your commit locally with `git commit --amend`, but you'll probably need the `--force-with-lease` option for pushing, i.e. `git push --force-with-lease`.

**Comment by dstorrs** [comment]
> @dstorrs, thanks for your PR! :-) My feedback, apart from the feedback in the previous comment :-) ...
>

> Please change your commit message to follow https://cbea.ms/git-commit/ . In your case you only need to change the subject line, but if you want to explain a bit more why you wrote what you wrote (e.g. a motivation for the specific example), the commit message body may be a good place.

Done.

>     * I think a bullet point style works better for the notes. Can you please split the PR in sensible bullet points (maybe one for the definition at the start, one for the example and one for `curry` and `curryr`?) I think splitting notes is useful because it makes it easier for others to add more notes. If the "Currying" section would be your PR, it may seem to others that this essentially is the glossary entry and might be discouraged to add more notes/thoughts.


I have no idea what this means in this context.  There's nothing in my PR that makes sense to me as bullet points.  If you want to redo it yourself then I'll look at what you do and keep it in mind if I make further contributions.


For the record, I agree with Simon Schlee here: https://racket.discourse.group/t/racket-glossary/916/12?u=dstorrs   To expand: what you're creating here would be better implemented as part of the Guide, not as a separate document.  The value proposition of this project is that it's vastly easier to contribute to a Markdown document than a Scribble document, especially one that's spread across multiple files with unintuitive structure the way the Racket documentation is.  The more demands you make on how PRs are structured, the less interest people are going to have in doing them.

**Comment by sschwarzer** [comment]
> For the record, I agree with Simon Schlee here: [https://racket.discourse.group/t/racket-glossary/916/12](https://racket.discourse.group/t/racket-glossary/916/12?u=dstorrs) [...]

I replied to this in our discussion on the Racket forum:

> The value proposition of this project is that it's vastly easier to contribute to a Markdown document than a Scribble document, especially one that's spread across multiple files with unintuitive structure the way the Racket documentation is.

From my perspective the main goal of the Racket Glossary is to make it easier for beginning and intermediate Racket users to understand what are basic, intermediate and advanced concepts, so they're not overwhelmed by stuff where they don't know what's important or even what a concept means in the first place. The use of Markdown is "only" to make contributions easier; in my opinion it's quite unrelated to what the glossary is going to be in the end.

> what you're creating here would be better implemented as part of the Guide, not as a separate document.

I don't think what I'd like to achieve with the glossary can be done in the Racket Guide, or only as a relatively big change to the contents of the Racket guide (see also [this post](https://racket.discourse.group/t/learning-racket-scheme-how-do-you-get-to-the-practicing-stage/901/24)). That said, my wish would be that eventually the glossary would become part of the official Racket documentation. I have no idea if it should be somehow merged into the Racket Guide, become an appendix to the Racket Guide, become a third document or whether it should stay an independent package. However, I'm thinking making this a standalone package for now would give me/us more freedom with experimenting with the form of the glossary. At the moment, I don't have an idea how the glossary could be combined with the Racket guide. I'm not saying it's not possible, only that I don't know how it could be done.

**Pull request merged**
